### ISSUE TITLE
Error: Cannot find module 'parse-dashboard'

### ISSUE THREAD

**Issue by LynanBreeze** [jaweii/Parse-JavaScript-translation#1]
**Platform:** Windows 10 64 Bit
**Node-version:** 8.9.0
**Error:** Cannot find module 'parse-dashboard'
**And During installing dependencies these occured:**
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Jerem\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jerem\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Projects\node\ParseServer\node_modules\_kerberos@0.0.23@kerberos
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by jaweii** [comment]
补上依赖项重试：
cnpm install parse-dashboard --save
